baseURL = 'https://rezepte.lichtensteiger.pro/'
languageCode = 'de-ch'
title = 'Familien Rezepte'
theme = 'lugo'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
